#开发配置
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/codetest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dsptest
    password: dsptest
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.example.mybatisdemo.entity
  mapperLocations: classpath:mapper/*.xml